-- TRACS auth schema.

CREATE TABLE IF NOT EXISTS `tracs_users` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `phone` VARCHAR(50) DEFAULT NULL,
  `position` VARCHAR(120) DEFAULT NULL,
  `password` VARCHAR(255) NOT NULL,
  `name` VARCHAR(100) NOT NULL DEFAULT '',
  `username` VARCHAR(80) DEFAULT NULL,
  `role` ENUM('admin','operator','viewer') NOT NULL DEFAULT 'operator',
  `is_active` TINYINT(1) NOT NULL DEFAULT 1,
  `status` ENUM('active','inactive','suspended') NOT NULL DEFAULT 'active',
  `division_id` INT UNSIGNED DEFAULT NULL,
  `role_id` INT UNSIGNED DEFAULT NULL,
  `shift_preference` VARCHAR(60) DEFAULT NULL,
  `avatar_initials_color` VARCHAR(20) DEFAULT NULL,
  `created_by` INT UNSIGNED DEFAULT NULL,
  `updated_by` INT UNSIGNED DEFAULT NULL,
  `last_login_at` DATETIME DEFAULT NULL,
  `last_activity_at` DATETIME DEFAULT NULL,
  `last_password_change_at` DATETIME DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_users_email` (`email`),
  UNIQUE KEY `uq_tracs_users_username` (`username`),
  INDEX `idx_users_active` (`is_active`),
  INDEX `idx_users_role` (`role`),
  INDEX `idx_tracs_users_status` (`status`),
  INDEX `idx_tracs_users_role_id` (`role_id`),
  INDEX `idx_tracs_users_division_id` (`division_id`),
  INDEX `idx_tracs_users_last_activity` (`last_activity_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `tracs_login_attempts` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `identifier_hash` CHAR(64) NOT NULL,
  `identifier_display` VARCHAR(191) DEFAULT NULL,
  `ip_address` VARCHAR(45) NOT NULL DEFAULT '',
  `user_id` INT DEFAULT NULL,
  `failed_attempts` INT UNSIGNED NOT NULL DEFAULT 0,
  `first_failed_at` DATETIME DEFAULT NULL,
  `last_failed_at` DATETIME DEFAULT NULL,
  `locked_until` DATETIME DEFAULT NULL,
  `captcha_required_until` DATETIME DEFAULT NULL,
  `last_result` ENUM('failed','locked','success') NOT NULL DEFAULT 'failed',
  `user_agent` VARCHAR(500) DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_login_attempt_identifier_ip` (`identifier_hash`, `ip_address`),
  KEY `idx_login_attempt_identifier` (`identifier_hash`, `last_failed_at`),
  KEY `idx_login_attempt_ip` (`ip_address`, `last_failed_at`),
  KEY `idx_login_attempt_lock` (`locked_until`),
  KEY `idx_login_attempt_captcha` (`captcha_required_until`),
  KEY `idx_login_attempt_user` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `tracs_auth_events` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `event_type` VARCHAR(60) NOT NULL,
  `result` VARCHAR(40) NOT NULL,
  `user_id` INT DEFAULT NULL,
  `identifier` VARCHAR(191) DEFAULT NULL,
  `ip_address` VARCHAR(45) DEFAULT NULL,
  `user_agent` VARCHAR(500) DEFAULT NULL,
  `reason` VARCHAR(255) DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_auth_events_created` (`created_at`),
  KEY `idx_auth_events_type` (`event_type`, `result`),
  KEY `idx_auth_events_user` (`user_id`),
  KEY `idx_auth_events_identifier` (`identifier`),
  KEY `idx_auth_events_ip` (`ip_address`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
