-- TRACS auth schema.

CREATE TABLE IF NOT EXISTS `tracs_users` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `phone` VARCHAR(50) DEFAULT NULL,
  `position` VARCHAR(120) DEFAULT NULL,
  `password` VARCHAR(255) NOT NULL,
  `name` VARCHAR(100) NOT NULL DEFAULT '',
  `username` VARCHAR(80) DEFAULT NULL,
  `role` ENUM('admin','operator','viewer') NOT NULL DEFAULT 'operator',
  `is_active` TINYINT(1) NOT NULL DEFAULT 1,
  `status` ENUM('active','inactive','suspended') NOT NULL DEFAULT 'active',
  `division_id` INT UNSIGNED DEFAULT NULL,
  `role_id` INT UNSIGNED DEFAULT NULL,
  `shift_preference` VARCHAR(60) DEFAULT NULL,
  `avatar_initials_color` VARCHAR(20) DEFAULT NULL,
  `created_by` INT UNSIGNED DEFAULT NULL,
  `updated_by` INT UNSIGNED DEFAULT NULL,
  `last_login_at` DATETIME DEFAULT NULL,
  `last_activity_at` DATETIME DEFAULT NULL,
  `last_password_change_at` DATETIME DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_users_email` (`email`),
  UNIQUE KEY `uq_tracs_users_username` (`username`),
  INDEX `idx_users_active` (`is_active`),
  INDEX `idx_users_role` (`role`),
  INDEX `idx_tracs_users_status` (`status`),
  INDEX `idx_tracs_users_role_id` (`role_id`),
  INDEX `idx_tracs_users_division_id` (`division_id`),
  INDEX `idx_tracs_users_last_activity` (`last_activity_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
