<?php require '_bootstrap.php';
$id = (int)($body['id'] ?? 0);
if (!$id) fail('ID required');
$stmt = $conn->prepare("SELECT title FROM tracs_cases WHERE id=? AND user_id=? LIMIT 1");
if (!$stmt) fail('Database error', 500);
$stmt->bind_param('ii', $id, $uid);
$stmt->execute();
$row = $stmt->get_result()->fetch_assoc();
$stmt->close();
if (!$row) fail('Case not found', 404);
$stmt = $conn->prepare("DELETE FROM tracs_cases WHERE id=? AND user_id=?");
if (!$stmt) fail('Database error', 500);
$stmt->bind_param('ii', $id, $uid);
$stmt->execute();
$stmt->close();
logAct($conn,$uid,'deleted','Cases',"Deleted case: {$row['title']}",$id);
ok(null,'Case deleted');
