<?php require '_bootstrap.php';
$conn->query("CREATE TABLE IF NOT EXISTS tracs_domains (id INT AUTO_INCREMENT PRIMARY KEY,user_id INT NOT NULL,domain VARCHAR(253) NOT NULL,registrar VARCHAR(200),expires_at DATE,ssl_active TINYINT(1) DEFAULT 0,auto_renew TINYINT(1) DEFAULT 0,notes VARCHAR(500),created_at DATETIME DEFAULT NOW(),updated_at DATETIME DEFAULT NOW(),INDEX(user_id))");
tracs_ensure_creator_columns($conn, 'tracs_domains', 'user_id');
$domain=trim($body['domain']??''); if(!$domain) fail('Domain required');
$registrar=$body['registrar']??'';
$expires=$body['expires_at']?date('Y-m-d',strtotime($body['expires_at'])):null;
$ssl=(int)(bool)($body['ssl_active']??0); $auto=(int)(bool)($body['auto_renew']??0);
$notes=$body['notes']??'';
$stmt=$conn->prepare("INSERT INTO tracs_domains (user_id,domain,registrar,expires_at,ssl_active,auto_renew,notes,created_by,created_by_name) VALUES (?,?,?,?,?,?,?,?,?)");
$stmt->bind_param('isssiisis',$uid,$domain,$registrar,$expires,$ssl,$auto,$notes,$uid,$creator_name);
if(!$stmt->execute()) fail('DB error: '.$conn->error);
$id=$stmt->insert_id; $stmt->close();
logAct($conn,$uid,'created','Domains',"Added domain: {$domain}",$id);
ok(['id'=>$id],'Domain added');
