<?php require '_bootstrap.php';
$id=(int)($body['id']??0); if(!$id) fail('ID required');
$done=(int)(bool)($body['is_completed']??0);
$stmt=$conn->prepare("UPDATE tracs_reminders SET is_completed=?,updated_at=NOW() WHERE id=? AND user_id=?");
$stmt->bind_param('iii',$done,$id,$uid);
if(!$stmt->execute()||$stmt->affected_rows===0) fail('Not found',404);
$stmt->close();
$act=$done?'completed':'uncompleted';
logAct($conn,$uid,$act,'Reminders',"Reminder marked as ".($done?'complete':'incomplete'),$id);
if ($done) tickerEvent($conn, $uid, "Reminder completed: reminder #{$id}", 'success', 'reminders', $id);
ok(null,'Updated');
