<?php require '_bootstrap.php';
$id=(int)($body['id']??$_GET['id']??0); if(!$id) fail('ID required');
$stmt = $conn->prepare("SELECT * FROM tracs_reminders WHERE id=? AND user_id=? LIMIT 1");
if (!$stmt) fail('Database error', 500);
$stmt->bind_param('ii', $id, $uid);
$stmt->execute();
$row = $stmt->get_result()->fetch_assoc();
$stmt->close();
if(!$row) fail('Not found',404);
ok($row);
