CREATE TABLE IF NOT EXISTS `tracs_dobby_event_outbox` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `event_id` CHAR(36) NOT NULL,
  `source` VARCHAR(80) NOT NULL DEFAULT 'tracs',
  `event_type` VARCHAR(120) NOT NULL,
  `category` VARCHAR(40) NOT NULL,
  `severity` VARCHAR(20) NOT NULL DEFAULT 'info',
  `resource` VARCHAR(160) NOT NULL,
  `actor_json` JSON NULL,
  `summary` VARCHAR(255) NOT NULL,
  `metadata_json` JSON NULL,
  `occurred_at` DATETIME NOT NULL,
  `schema_version` TINYINT UNSIGNED NOT NULL DEFAULT 1,
  `correlation_id` VARCHAR(120) NULL,
  `status` ENUM('queued','sent','failed') NOT NULL DEFAULT 'queued',
  `attempts` INT UNSIGNED NOT NULL DEFAULT 0,
  `next_attempt_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `last_error` VARCHAR(255) NULL,
  `delivered_at` DATETIME NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_dobby_event_id` (`event_id`),
  KEY `idx_dobby_outbox_delivery` (`status`, `next_attempt_at`, `id`),
  KEY `idx_dobby_outbox_type` (`event_type`, `occurred_at`),
  KEY `idx_dobby_outbox_correlation` (`correlation_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
